// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: userCommandService.proto

package nowin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLoginUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLoginUserRequest) Reset() {
	*x = GetLoginUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userCommandService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginUserRequest) ProtoMessage() {}

func (x *GetLoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userCommandService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginUserRequest.ProtoReflect.Descriptor instead.
func (*GetLoginUserRequest) Descriptor() ([]byte, []int) {
	return file_userCommandService_proto_rawDescGZIP(), []int{0}
}

type GetLoginUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLoginUserResponse) Reset() {
	*x = GetLoginUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userCommandService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginUserResponse) ProtoMessage() {}

func (x *GetLoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userCommandService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginUserResponse.ProtoReflect.Descriptor instead.
func (*GetLoginUserResponse) Descriptor() ([]byte, []int) {
	return file_userCommandService_proto_rawDescGZIP(), []int{1}
}

var File_userCommandService_proto protoreflect.FileDescriptor

var file_userCommandService_proto_rawDesc = []byte{
	0x0a, 0x18, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x63, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x66, 0x74, 0x69, 0x61, 0x2d, 0x69, 0x6e, 0x63,
	0x2f, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x2d, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x3b, 0x6e, 0x6f, 0x77, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userCommandService_proto_rawDescOnce sync.Once
	file_userCommandService_proto_rawDescData = file_userCommandService_proto_rawDesc
)

func file_userCommandService_proto_rawDescGZIP() []byte {
	file_userCommandService_proto_rawDescOnce.Do(func() {
		file_userCommandService_proto_rawDescData = protoimpl.X.CompressGZIP(file_userCommandService_proto_rawDescData)
	})
	return file_userCommandService_proto_rawDescData
}

var file_userCommandService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_userCommandService_proto_goTypes = []interface{}{
	(*GetLoginUserRequest)(nil),  // 0: example.GetLoginUserRequest
	(*GetLoginUserResponse)(nil), // 1: example.GetLoginUserResponse
}
var file_userCommandService_proto_depIdxs = []int32{
	0, // 0: example.UserCommandService.GetLoginUser:input_type -> example.GetLoginUserRequest
	1, // 1: example.UserCommandService.GetLoginUser:output_type -> example.GetLoginUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userCommandService_proto_init() }
func file_userCommandService_proto_init() {
	if File_userCommandService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userCommandService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLoginUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userCommandService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLoginUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userCommandService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userCommandService_proto_goTypes,
		DependencyIndexes: file_userCommandService_proto_depIdxs,
		MessageInfos:      file_userCommandService_proto_msgTypes,
	}.Build()
	File_userCommandService_proto = out.File
	file_userCommandService_proto_rawDesc = nil
	file_userCommandService_proto_goTypes = nil
	file_userCommandService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserCommandServiceClient is the client API for UserCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserCommandServiceClient interface {
	GetLoginUser(ctx context.Context, in *GetLoginUserRequest, opts ...grpc.CallOption) (*GetLoginUserResponse, error)
}

type userCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCommandServiceClient(cc grpc.ClientConnInterface) UserCommandServiceClient {
	return &userCommandServiceClient{cc}
}

func (c *userCommandServiceClient) GetLoginUser(ctx context.Context, in *GetLoginUserRequest, opts ...grpc.CallOption) (*GetLoginUserResponse, error) {
	out := new(GetLoginUserResponse)
	err := c.cc.Invoke(ctx, "/example.UserCommandService/GetLoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCommandServiceServer is the server API for UserCommandService service.
type UserCommandServiceServer interface {
	GetLoginUser(context.Context, *GetLoginUserRequest) (*GetLoginUserResponse, error)
}

// UnimplementedUserCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserCommandServiceServer struct {
}

func (*UnimplementedUserCommandServiceServer) GetLoginUser(context.Context, *GetLoginUserRequest) (*GetLoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoginUser not implemented")
}

func RegisterUserCommandServiceServer(s *grpc.Server, srv UserCommandServiceServer) {
	s.RegisterService(&_UserCommandService_serviceDesc, srv)
}

func _UserCommandService_GetLoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCommandServiceServer).GetLoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.UserCommandService/GetLoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCommandServiceServer).GetLoginUser(ctx, req.(*GetLoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.UserCommandService",
	HandlerType: (*UserCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLoginUser",
			Handler:    _UserCommandService_GetLoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userCommandService.proto",
}
